### ISSUE TITLE
Tracking v2

### ISSUE THREAD

**Issue by pixeleet** [type-driven/hello_deno#21]
Wishes ideas and everything goes here for v2
- [ ] Create a small production ready app
- [ ] Auth
- [ ] Logging
- [ ] Instrumentation
- [ ] Using Deno KV
- [ ] Using FUN
- [ ] Prompt based scaffolding?
